default: &default
  adapter: postgresql # Mantemos o default como postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default # Herda o adaptador postgresql do default
  database: finance_tracker_development # Escolha um nome para o banco de dados de desenvolvimento
  username: <%= ENV['DATABASE_USER'] || 'rafaelmoncores' %> # Seu usuário do PostgreSQL
  password: <%= ENV['DATABASE_PASSWORD'] || '' %> # Sua senha do PostgreSQL (se houver, ou deixe em branco)
  host: localhost # Onde o PostgreSQL está rodando
  port: 5432 # Porta padrão do PostgreSQL

test:
  <<: *default
  database: finance_tracker_test # Nome do banco de dados de teste
  username: <%= ENV['DATABASE_USER'] || 'rafaelmoncores' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>